/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables.records;


import cn.treeshell.echo.model.entity.tables.Article;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 文章表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleRecord extends UpdatableRecordImpl<ArticleRecord> implements Record14<Integer, Integer, String, Integer, String, String, Byte, String, Integer, Integer, Integer, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1194979926;

    /**
     * Setter for <code>echo.article.id</code>. id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>echo.article.id</code>. id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>echo.article.user_id</code>. 发表者id
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>echo.article.user_id</code>. 发表者id
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>echo.article.title</code>. 标题
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>echo.article.title</code>. 标题
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>echo.article.content_id</code>. 文章内容id
     */
    public void setContentId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>echo.article.content_id</code>. 文章内容id
     */
    public Integer getContentId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>echo.article.digest</code>. 摘要
     */
    public void setDigest(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>echo.article.digest</code>. 摘要
     */
    public String getDigest() {
        return (String) get(4);
    }

    /**
     * Setter for <code>echo.article.image_url</code>. 主图地址
     */
    public void setImageUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>echo.article.image_url</code>. 主图地址
     */
    public String getImageUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>echo.article.type</code>. 0：原创，1：转载，2：翻译
     */
    public void setType(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>echo.article.type</code>. 0：原创，1：转载，2：翻译
     */
    public Byte getType() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>echo.article.origin_url</code>. 转载/翻译的原文链接
     */
    public void setOriginUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>echo.article.origin_url</code>. 转载/翻译的原文链接
     */
    public String getOriginUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>echo.article.likes</code>. 点赞/喜欢数
     */
    public void setLikes(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>echo.article.likes</code>. 点赞/喜欢数
     */
    public Integer getLikes() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>echo.article.tag_id</code>. 标签id
     */
    public void setTagId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>echo.article.tag_id</code>. 标签id
     */
    public Integer getTagId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>echo.article.category_id</code>. 分类id
     */
    public void setCategoryId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>echo.article.category_id</code>. 分类id
     */
    public Integer getCategoryId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>echo.article.active</code>. 0：未删除，1：已删除
     */
    public void setActive(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>echo.article.active</code>. 0：未删除，1：已删除
     */
    public Byte getActive() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>echo.article.create_time</code>. 创建日期
     */
    public void setCreateTime(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>echo.article.create_time</code>. 创建日期
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>echo.article.update_time</code>. 修改日期
     */
    public void setUpdateTime(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>echo.article.update_time</code>. 修改日期
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, Integer, String, Integer, String, String, Byte, String, Integer, Integer, Integer, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, Integer, String, Integer, String, String, Byte, String, Integer, Integer, Integer, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Article.ARTICLE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Article.ARTICLE.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Article.ARTICLE.TITLE;
    }

    @Override
    public Field<Integer> field4() {
        return Article.ARTICLE.CONTENT_ID;
    }

    @Override
    public Field<String> field5() {
        return Article.ARTICLE.DIGEST;
    }

    @Override
    public Field<String> field6() {
        return Article.ARTICLE.IMAGE_URL;
    }

    @Override
    public Field<Byte> field7() {
        return Article.ARTICLE.TYPE;
    }

    @Override
    public Field<String> field8() {
        return Article.ARTICLE.ORIGIN_URL;
    }

    @Override
    public Field<Integer> field9() {
        return Article.ARTICLE.LIKES;
    }

    @Override
    public Field<Integer> field10() {
        return Article.ARTICLE.TAG_ID;
    }

    @Override
    public Field<Integer> field11() {
        return Article.ARTICLE.CATEGORY_ID;
    }

    @Override
    public Field<Byte> field12() {
        return Article.ARTICLE.ACTIVE;
    }

    @Override
    public Field<Timestamp> field13() {
        return Article.ARTICLE.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field14() {
        return Article.ARTICLE.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public Integer component4() {
        return getContentId();
    }

    @Override
    public String component5() {
        return getDigest();
    }

    @Override
    public String component6() {
        return getImageUrl();
    }

    @Override
    public Byte component7() {
        return getType();
    }

    @Override
    public String component8() {
        return getOriginUrl();
    }

    @Override
    public Integer component9() {
        return getLikes();
    }

    @Override
    public Integer component10() {
        return getTagId();
    }

    @Override
    public Integer component11() {
        return getCategoryId();
    }

    @Override
    public Byte component12() {
        return getActive();
    }

    @Override
    public Timestamp component13() {
        return getCreateTime();
    }

    @Override
    public Timestamp component14() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public Integer value4() {
        return getContentId();
    }

    @Override
    public String value5() {
        return getDigest();
    }

    @Override
    public String value6() {
        return getImageUrl();
    }

    @Override
    public Byte value7() {
        return getType();
    }

    @Override
    public String value8() {
        return getOriginUrl();
    }

    @Override
    public Integer value9() {
        return getLikes();
    }

    @Override
    public Integer value10() {
        return getTagId();
    }

    @Override
    public Integer value11() {
        return getCategoryId();
    }

    @Override
    public Byte value12() {
        return getActive();
    }

    @Override
    public Timestamp value13() {
        return getCreateTime();
    }

    @Override
    public Timestamp value14() {
        return getUpdateTime();
    }

    @Override
    public ArticleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ArticleRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public ArticleRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ArticleRecord value4(Integer value) {
        setContentId(value);
        return this;
    }

    @Override
    public ArticleRecord value5(String value) {
        setDigest(value);
        return this;
    }

    @Override
    public ArticleRecord value6(String value) {
        setImageUrl(value);
        return this;
    }

    @Override
    public ArticleRecord value7(Byte value) {
        setType(value);
        return this;
    }

    @Override
    public ArticleRecord value8(String value) {
        setOriginUrl(value);
        return this;
    }

    @Override
    public ArticleRecord value9(Integer value) {
        setLikes(value);
        return this;
    }

    @Override
    public ArticleRecord value10(Integer value) {
        setTagId(value);
        return this;
    }

    @Override
    public ArticleRecord value11(Integer value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public ArticleRecord value12(Byte value) {
        setActive(value);
        return this;
    }

    @Override
    public ArticleRecord value13(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public ArticleRecord value14(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public ArticleRecord values(Integer value1, Integer value2, String value3, Integer value4, String value5, String value6, Byte value7, String value8, Integer value9, Integer value10, Integer value11, Byte value12, Timestamp value13, Timestamp value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleRecord
     */
    public ArticleRecord() {
        super(Article.ARTICLE);
    }

    /**
     * Create a detached, initialised ArticleRecord
     */
    public ArticleRecord(Integer id, Integer userId, String title, Integer contentId, String digest, String imageUrl, Byte type, String originUrl, Integer likes, Integer tagId, Integer categoryId, Byte active, Timestamp createTime, Timestamp updateTime) {
        super(Article.ARTICLE);

        set(0, id);
        set(1, userId);
        set(2, title);
        set(3, contentId);
        set(4, digest);
        set(5, imageUrl);
        set(6, type);
        set(7, originUrl);
        set(8, likes);
        set(9, tagId);
        set(10, categoryId);
        set(11, active);
        set(12, createTime);
        set(13, updateTime);
    }
}
