/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables.records;


import cn.treeshell.echo.model.entity.tables.ArticleContent;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 文章内容表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleContentRecord extends UpdatableRecordImpl<ArticleContentRecord> implements Record5<Integer, String, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = -2063402718;

    /**
     * Setter for <code>echo.article_content.id</code>. id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>echo.article_content.id</code>. id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>echo.article_content.content</code>. 内容
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>echo.article_content.content</code>. 内容
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>echo.article_content.active</code>. 0：未删除，1：已删除
     */
    public void setActive(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>echo.article_content.active</code>. 0：未删除，1：已删除
     */
    public Byte getActive() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>echo.article_content.create_time</code>. 创建日期
     */
    public void setCreateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>echo.article_content.create_time</code>. 创建日期
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>echo.article_content.update_time</code>. 修改日期
     */
    public void setUpdateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>echo.article_content.update_time</code>. 修改日期
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ArticleContent.ARTICLE_CONTENT.ID;
    }

    @Override
    public Field<String> field2() {
        return ArticleContent.ARTICLE_CONTENT.CONTENT;
    }

    @Override
    public Field<Byte> field3() {
        return ArticleContent.ARTICLE_CONTENT.ACTIVE;
    }

    @Override
    public Field<Timestamp> field4() {
        return ArticleContent.ARTICLE_CONTENT.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field5() {
        return ArticleContent.ARTICLE_CONTENT.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getContent();
    }

    @Override
    public Byte component3() {
        return getActive();
    }

    @Override
    public Timestamp component4() {
        return getCreateTime();
    }

    @Override
    public Timestamp component5() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getContent();
    }

    @Override
    public Byte value3() {
        return getActive();
    }

    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    @Override
    public Timestamp value5() {
        return getUpdateTime();
    }

    @Override
    public ArticleContentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ArticleContentRecord value2(String value) {
        setContent(value);
        return this;
    }

    @Override
    public ArticleContentRecord value3(Byte value) {
        setActive(value);
        return this;
    }

    @Override
    public ArticleContentRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public ArticleContentRecord value5(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public ArticleContentRecord values(Integer value1, String value2, Byte value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleContentRecord
     */
    public ArticleContentRecord() {
        super(ArticleContent.ARTICLE_CONTENT);
    }

    /**
     * Create a detached, initialised ArticleContentRecord
     */
    public ArticleContentRecord(Integer id, String content, Byte active, Timestamp createTime, Timestamp updateTime) {
        super(ArticleContent.ARTICLE_CONTENT);

        set(0, id);
        set(1, content);
        set(2, active);
        set(3, createTime);
        set(4, updateTime);
    }
}
