/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables.records;


import cn.treeshell.echo.model.entity.tables.Category;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 文章分类表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryRecord extends UpdatableRecordImpl<CategoryRecord> implements Record6<Integer, Integer, String, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 214165237;

    /**
     * Setter for <code>echo.category.id</code>. id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>echo.category.id</code>. id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>echo.category.parent_id</code>. 当前分类父菜单id
     */
    public void setParentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>echo.category.parent_id</code>. 当前分类父菜单id
     */
    public Integer getParentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>echo.category.name</code>. 分类名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>echo.category.name</code>. 分类名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>echo.category.active</code>. 0：未删除，1：已删除
     */
    public void setActive(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>echo.category.active</code>. 0：未删除，1：已删除
     */
    public Byte getActive() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>echo.category.create_time</code>. 创建日期
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>echo.category.create_time</code>. 创建日期
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>echo.category.update_time</code>. 修改日期
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>echo.category.update_time</code>. 修改日期
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Category.CATEGORY.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Category.CATEGORY.PARENT_ID;
    }

    @Override
    public Field<String> field3() {
        return Category.CATEGORY.NAME;
    }

    @Override
    public Field<Byte> field4() {
        return Category.CATEGORY.ACTIVE;
    }

    @Override
    public Field<Timestamp> field5() {
        return Category.CATEGORY.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field6() {
        return Category.CATEGORY.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getParentId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Byte component4() {
        return getActive();
    }

    @Override
    public Timestamp component5() {
        return getCreateTime();
    }

    @Override
    public Timestamp component6() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getParentId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Byte value4() {
        return getActive();
    }

    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    @Override
    public CategoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CategoryRecord value2(Integer value) {
        setParentId(value);
        return this;
    }

    @Override
    public CategoryRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public CategoryRecord value4(Byte value) {
        setActive(value);
        return this;
    }

    @Override
    public CategoryRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public CategoryRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public CategoryRecord values(Integer value1, Integer value2, String value3, Byte value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoryRecord
     */
    public CategoryRecord() {
        super(Category.CATEGORY);
    }

    /**
     * Create a detached, initialised CategoryRecord
     */
    public CategoryRecord(Integer id, Integer parentId, String name, Byte active, Timestamp createTime, Timestamp updateTime) {
        super(Category.CATEGORY);

        set(0, id);
        set(1, parentId);
        set(2, name);
        set(3, active);
        set(4, createTime);
        set(5, updateTime);
    }
}
