/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables.records;


import cn.treeshell.echo.model.entity.tables.CommentLike;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户点赞评论表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentLikeRecord extends UpdatableRecordImpl<CommentLikeRecord> implements Record7<Integer, Integer, Integer, Integer, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1319031667;

    /**
     * Setter for <code>echo.comment_like.id</code>. id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>echo.comment_like.id</code>. id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>echo.comment_like.comment_id</code>. 评论id
     */
    public void setCommentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>echo.comment_like.comment_id</code>. 评论id
     */
    public Integer getCommentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>echo.comment_like.user_id</code>. 收藏用户id
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>echo.comment_like.user_id</code>. 收藏用户id
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>echo.comment_like.publisher_id</code>. 发布评论用户id
     */
    public void setPublisherId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>echo.comment_like.publisher_id</code>. 发布评论用户id
     */
    public Integer getPublisherId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>echo.comment_like.active</code>. 0：未删除，1：已删除
     */
    public void setActive(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>echo.comment_like.active</code>. 0：未删除，1：已删除
     */
    public Byte getActive() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>echo.comment_like.create_time</code>. 创建日期
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>echo.comment_like.create_time</code>. 创建日期
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>echo.comment_like.update_time</code>. 修改日期
     */
    public void setUpdateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>echo.comment_like.update_time</code>. 修改日期
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, Integer, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, Integer, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CommentLike.COMMENT_LIKE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return CommentLike.COMMENT_LIKE.COMMENT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return CommentLike.COMMENT_LIKE.USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return CommentLike.COMMENT_LIKE.PUBLISHER_ID;
    }

    @Override
    public Field<Byte> field5() {
        return CommentLike.COMMENT_LIKE.ACTIVE;
    }

    @Override
    public Field<Timestamp> field6() {
        return CommentLike.COMMENT_LIKE.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field7() {
        return CommentLike.COMMENT_LIKE.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCommentId();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public Integer component4() {
        return getPublisherId();
    }

    @Override
    public Byte component5() {
        return getActive();
    }

    @Override
    public Timestamp component6() {
        return getCreateTime();
    }

    @Override
    public Timestamp component7() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCommentId();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public Integer value4() {
        return getPublisherId();
    }

    @Override
    public Byte value5() {
        return getActive();
    }

    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    @Override
    public Timestamp value7() {
        return getUpdateTime();
    }

    @Override
    public CommentLikeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CommentLikeRecord value2(Integer value) {
        setCommentId(value);
        return this;
    }

    @Override
    public CommentLikeRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public CommentLikeRecord value4(Integer value) {
        setPublisherId(value);
        return this;
    }

    @Override
    public CommentLikeRecord value5(Byte value) {
        setActive(value);
        return this;
    }

    @Override
    public CommentLikeRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public CommentLikeRecord value7(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public CommentLikeRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Byte value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentLikeRecord
     */
    public CommentLikeRecord() {
        super(CommentLike.COMMENT_LIKE);
    }

    /**
     * Create a detached, initialised CommentLikeRecord
     */
    public CommentLikeRecord(Integer id, Integer commentId, Integer userId, Integer publisherId, Byte active, Timestamp createTime, Timestamp updateTime) {
        super(CommentLike.COMMENT_LIKE);

        set(0, id);
        set(1, commentId);
        set(2, userId);
        set(3, publisherId);
        set(4, active);
        set(5, createTime);
        set(6, updateTime);
    }
}
