/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables.records;


import cn.treeshell.echo.model.entity.tables.Feedback;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 反馈表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeedbackRecord extends UpdatableRecordImpl<FeedbackRecord> implements Record8<Integer, String, String, Integer, Byte, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 503864258;

    /**
     * Setter for <code>echo.feedback.id</code>. id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>echo.feedback.id</code>. id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>echo.feedback.title</code>. 反馈标题
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>echo.feedback.title</code>. 反馈标题
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>echo.feedback.content</code>. 反馈内容
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>echo.feedback.content</code>. 反馈内容
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>echo.feedback.user_id</code>. 反馈人id
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>echo.feedback.user_id</code>. 反馈人id
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>echo.feedback.status</code>. 0：未解决，1：已解决
     */
    public void setStatus(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>echo.feedback.status</code>. 0：未解决，1：已解决
     */
    public Byte getStatus() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>echo.feedback.active</code>. 0：未删除，1：已删除
     */
    public void setActive(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>echo.feedback.active</code>. 0：未删除，1：已删除
     */
    public Byte getActive() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>echo.feedback.create_time</code>. 创建日期
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>echo.feedback.create_time</code>. 创建日期
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>echo.feedback.update_time</code>. 修改日期
     */
    public void setUpdateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>echo.feedback.update_time</code>. 修改日期
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, Integer, Byte, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, Integer, Byte, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Feedback.FEEDBACK.ID;
    }

    @Override
    public Field<String> field2() {
        return Feedback.FEEDBACK.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Feedback.FEEDBACK.CONTENT;
    }

    @Override
    public Field<Integer> field4() {
        return Feedback.FEEDBACK.USER_ID;
    }

    @Override
    public Field<Byte> field5() {
        return Feedback.FEEDBACK.STATUS;
    }

    @Override
    public Field<Byte> field6() {
        return Feedback.FEEDBACK.ACTIVE;
    }

    @Override
    public Field<Timestamp> field7() {
        return Feedback.FEEDBACK.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field8() {
        return Feedback.FEEDBACK.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getContent();
    }

    @Override
    public Integer component4() {
        return getUserId();
    }

    @Override
    public Byte component5() {
        return getStatus();
    }

    @Override
    public Byte component6() {
        return getActive();
    }

    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    @Override
    public Timestamp component8() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getContent();
    }

    @Override
    public Integer value4() {
        return getUserId();
    }

    @Override
    public Byte value5() {
        return getStatus();
    }

    @Override
    public Byte value6() {
        return getActive();
    }

    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    @Override
    public Timestamp value8() {
        return getUpdateTime();
    }

    @Override
    public FeedbackRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FeedbackRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public FeedbackRecord value3(String value) {
        setContent(value);
        return this;
    }

    @Override
    public FeedbackRecord value4(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public FeedbackRecord value5(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public FeedbackRecord value6(Byte value) {
        setActive(value);
        return this;
    }

    @Override
    public FeedbackRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public FeedbackRecord value8(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public FeedbackRecord values(Integer value1, String value2, String value3, Integer value4, Byte value5, Byte value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeedbackRecord
     */
    public FeedbackRecord() {
        super(Feedback.FEEDBACK);
    }

    /**
     * Create a detached, initialised FeedbackRecord
     */
    public FeedbackRecord(Integer id, String title, String content, Integer userId, Byte status, Byte active, Timestamp createTime, Timestamp updateTime) {
        super(Feedback.FEEDBACK);

        set(0, id);
        set(1, title);
        set(2, content);
        set(3, userId);
        set(4, status);
        set(5, active);
        set(6, createTime);
        set(7, updateTime);
    }
}
