/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables.records;


import cn.treeshell.echo.model.entity.tables.FriendLink;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 友链表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FriendLinkRecord extends UpdatableRecordImpl<FriendLinkRecord> implements Record8<Integer, String, String, String, String, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1676103804;

    /**
     * Setter for <code>echo.friend_link.id</code>. id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>echo.friend_link.id</code>. id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>echo.friend_link.title</code>. 博客标题
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>echo.friend_link.title</code>. 博客标题
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>echo.friend_link.url</code>. 博客地址
     */
    public void setUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>echo.friend_link.url</code>. 博客地址
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>echo.friend_link.image_url</code>. 博客图标地址
     */
    public void setImageUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>echo.friend_link.image_url</code>. 博客图标地址
     */
    public String getImageUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>echo.friend_link.email</code>. 联系人邮箱
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>echo.friend_link.email</code>. 联系人邮箱
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>echo.friend_link.active</code>. 0：未删除，1：已删除
     */
    public void setActive(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>echo.friend_link.active</code>. 0：未删除，1：已删除
     */
    public Byte getActive() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>echo.friend_link.create_time</code>. 创建日期
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>echo.friend_link.create_time</code>. 创建日期
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>echo.friend_link.update_time</code>. 修改日期
     */
    public void setUpdateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>echo.friend_link.update_time</code>. 修改日期
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, String, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, String, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FriendLink.FRIEND_LINK.ID;
    }

    @Override
    public Field<String> field2() {
        return FriendLink.FRIEND_LINK.TITLE;
    }

    @Override
    public Field<String> field3() {
        return FriendLink.FRIEND_LINK.URL;
    }

    @Override
    public Field<String> field4() {
        return FriendLink.FRIEND_LINK.IMAGE_URL;
    }

    @Override
    public Field<String> field5() {
        return FriendLink.FRIEND_LINK.EMAIL;
    }

    @Override
    public Field<Byte> field6() {
        return FriendLink.FRIEND_LINK.ACTIVE;
    }

    @Override
    public Field<Timestamp> field7() {
        return FriendLink.FRIEND_LINK.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field8() {
        return FriendLink.FRIEND_LINK.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getUrl();
    }

    @Override
    public String component4() {
        return getImageUrl();
    }

    @Override
    public String component5() {
        return getEmail();
    }

    @Override
    public Byte component6() {
        return getActive();
    }

    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    @Override
    public Timestamp component8() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getUrl();
    }

    @Override
    public String value4() {
        return getImageUrl();
    }

    @Override
    public String value5() {
        return getEmail();
    }

    @Override
    public Byte value6() {
        return getActive();
    }

    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    @Override
    public Timestamp value8() {
        return getUpdateTime();
    }

    @Override
    public FriendLinkRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FriendLinkRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public FriendLinkRecord value3(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public FriendLinkRecord value4(String value) {
        setImageUrl(value);
        return this;
    }

    @Override
    public FriendLinkRecord value5(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public FriendLinkRecord value6(Byte value) {
        setActive(value);
        return this;
    }

    @Override
    public FriendLinkRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public FriendLinkRecord value8(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public FriendLinkRecord values(Integer value1, String value2, String value3, String value4, String value5, Byte value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FriendLinkRecord
     */
    public FriendLinkRecord() {
        super(FriendLink.FRIEND_LINK);
    }

    /**
     * Create a detached, initialised FriendLinkRecord
     */
    public FriendLinkRecord(Integer id, String title, String url, String imageUrl, String email, Byte active, Timestamp createTime, Timestamp updateTime) {
        super(FriendLink.FRIEND_LINK);

        set(0, id);
        set(1, title);
        set(2, url);
        set(3, imageUrl);
        set(4, email);
        set(5, active);
        set(6, createTime);
        set(7, updateTime);
    }
}
