/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables.records;


import cn.treeshell.echo.model.entity.tables.Menu;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 系统菜单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MenuRecord extends UpdatableRecordImpl<MenuRecord> implements Record11<Integer, Integer, Byte, String, String, String, Byte, Byte, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1397666450;

    /**
     * Setter for <code>echo.menu.id</code>. id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>echo.menu.id</code>. id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>echo.menu.parent_id</code>. 当前菜单的父菜单id
     */
    public void setParentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>echo.menu.parent_id</code>. 当前菜单的父菜单id
     */
    public Integer getParentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>echo.menu.is_leaf</code>. 0：不是叶子节点，1：是叶子节点
     */
    public void setIsLeaf(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>echo.menu.is_leaf</code>. 0：不是叶子节点，1：是叶子节点
     */
    public Byte getIsLeaf() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>echo.menu.name</code>. 菜单名称
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>echo.menu.name</code>. 菜单名称
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>echo.menu.redirect_url</code>. 跳转URL
     */
    public void setRedirectUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>echo.menu.redirect_url</code>. 跳转URL
     */
    public String getRedirectUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>echo.menu.icon_url</code>. icon地址
     */
    public void setIconUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>echo.menu.icon_url</code>. icon地址
     */
    public String getIconUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>echo.menu.sort</code>. 菜单排序
     */
    public void setSort(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>echo.menu.sort</code>. 菜单排序
     */
    public Byte getSort() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>echo.menu.level</code>. 菜单层级
     */
    public void setLevel(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>echo.menu.level</code>. 菜单层级
     */
    public Byte getLevel() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>echo.menu.active</code>. 0：未删除，1：已删除
     */
    public void setActive(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>echo.menu.active</code>. 0：未删除，1：已删除
     */
    public Byte getActive() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>echo.menu.create_time</code>. 创建日期
     */
    public void setCreateTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>echo.menu.create_time</code>. 创建日期
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>echo.menu.update_time</code>. 修改日期
     */
    public void setUpdateTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>echo.menu.update_time</code>. 修改日期
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Integer, Byte, String, String, String, Byte, Byte, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, Integer, Byte, String, String, String, Byte, Byte, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Menu.MENU.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Menu.MENU.PARENT_ID;
    }

    @Override
    public Field<Byte> field3() {
        return Menu.MENU.IS_LEAF;
    }

    @Override
    public Field<String> field4() {
        return Menu.MENU.NAME;
    }

    @Override
    public Field<String> field5() {
        return Menu.MENU.REDIRECT_URL;
    }

    @Override
    public Field<String> field6() {
        return Menu.MENU.ICON_URL;
    }

    @Override
    public Field<Byte> field7() {
        return Menu.MENU.SORT;
    }

    @Override
    public Field<Byte> field8() {
        return Menu.MENU.LEVEL;
    }

    @Override
    public Field<Byte> field9() {
        return Menu.MENU.ACTIVE;
    }

    @Override
    public Field<Timestamp> field10() {
        return Menu.MENU.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field11() {
        return Menu.MENU.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getParentId();
    }

    @Override
    public Byte component3() {
        return getIsLeaf();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getRedirectUrl();
    }

    @Override
    public String component6() {
        return getIconUrl();
    }

    @Override
    public Byte component7() {
        return getSort();
    }

    @Override
    public Byte component8() {
        return getLevel();
    }

    @Override
    public Byte component9() {
        return getActive();
    }

    @Override
    public Timestamp component10() {
        return getCreateTime();
    }

    @Override
    public Timestamp component11() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getParentId();
    }

    @Override
    public Byte value3() {
        return getIsLeaf();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getRedirectUrl();
    }

    @Override
    public String value6() {
        return getIconUrl();
    }

    @Override
    public Byte value7() {
        return getSort();
    }

    @Override
    public Byte value8() {
        return getLevel();
    }

    @Override
    public Byte value9() {
        return getActive();
    }

    @Override
    public Timestamp value10() {
        return getCreateTime();
    }

    @Override
    public Timestamp value11() {
        return getUpdateTime();
    }

    @Override
    public MenuRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MenuRecord value2(Integer value) {
        setParentId(value);
        return this;
    }

    @Override
    public MenuRecord value3(Byte value) {
        setIsLeaf(value);
        return this;
    }

    @Override
    public MenuRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public MenuRecord value5(String value) {
        setRedirectUrl(value);
        return this;
    }

    @Override
    public MenuRecord value6(String value) {
        setIconUrl(value);
        return this;
    }

    @Override
    public MenuRecord value7(Byte value) {
        setSort(value);
        return this;
    }

    @Override
    public MenuRecord value8(Byte value) {
        setLevel(value);
        return this;
    }

    @Override
    public MenuRecord value9(Byte value) {
        setActive(value);
        return this;
    }

    @Override
    public MenuRecord value10(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public MenuRecord value11(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public MenuRecord values(Integer value1, Integer value2, Byte value3, String value4, String value5, String value6, Byte value7, Byte value8, Byte value9, Timestamp value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MenuRecord
     */
    public MenuRecord() {
        super(Menu.MENU);
    }

    /**
     * Create a detached, initialised MenuRecord
     */
    public MenuRecord(Integer id, Integer parentId, Byte isLeaf, String name, String redirectUrl, String iconUrl, Byte sort, Byte level, Byte active, Timestamp createTime, Timestamp updateTime) {
        super(Menu.MENU);

        set(0, id);
        set(1, parentId);
        set(2, isLeaf);
        set(3, name);
        set(4, redirectUrl);
        set(5, iconUrl);
        set(6, sort);
        set(7, level);
        set(8, active);
        set(9, createTime);
        set(10, updateTime);
    }
}
