/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables.records;


import cn.treeshell.echo.model.entity.tables.PrivateMessage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 悄悄话表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrivateMessageRecord extends UpdatableRecordImpl<PrivateMessageRecord> implements Record8<Integer, String, Integer, Integer, Byte, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -610991796;

    /**
     * Setter for <code>echo.private_message.id</code>. id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>echo.private_message.id</code>. id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>echo.private_message.content</code>. 悄悄话内容
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>echo.private_message.content</code>. 悄悄话内容
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>echo.private_message.user_id</code>. 发送悄悄话用户id
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>echo.private_message.user_id</code>. 发送悄悄话用户id
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>echo.private_message.replier_id</code>. 回复悄悄话用户id
     */
    public void setReplierId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>echo.private_message.replier_id</code>. 回复悄悄话用户id
     */
    public Integer getReplierId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>echo.private_message.active</code>. 0：未删除，1：已删除
     */
    public void setActive(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>echo.private_message.active</code>. 0：未删除，1：已删除
     */
    public Byte getActive() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>echo.private_message.create_time</code>. 创建日期
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>echo.private_message.create_time</code>. 创建日期
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>echo.private_message.update_time</code>. 修改日期
     */
    public void setUpdateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>echo.private_message.update_time</code>. 修改日期
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>echo.private_message.reply_time</code>. 回复日期
     */
    public void setReplyTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>echo.private_message.reply_time</code>. 回复日期
     */
    public Timestamp getReplyTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, Integer, Integer, Byte, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, Integer, Integer, Byte, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PrivateMessage.PRIVATE_MESSAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return PrivateMessage.PRIVATE_MESSAGE.CONTENT;
    }

    @Override
    public Field<Integer> field3() {
        return PrivateMessage.PRIVATE_MESSAGE.USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return PrivateMessage.PRIVATE_MESSAGE.REPLIER_ID;
    }

    @Override
    public Field<Byte> field5() {
        return PrivateMessage.PRIVATE_MESSAGE.ACTIVE;
    }

    @Override
    public Field<Timestamp> field6() {
        return PrivateMessage.PRIVATE_MESSAGE.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field7() {
        return PrivateMessage.PRIVATE_MESSAGE.UPDATE_TIME;
    }

    @Override
    public Field<Timestamp> field8() {
        return PrivateMessage.PRIVATE_MESSAGE.REPLY_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getContent();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public Integer component4() {
        return getReplierId();
    }

    @Override
    public Byte component5() {
        return getActive();
    }

    @Override
    public Timestamp component6() {
        return getCreateTime();
    }

    @Override
    public Timestamp component7() {
        return getUpdateTime();
    }

    @Override
    public Timestamp component8() {
        return getReplyTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getContent();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public Integer value4() {
        return getReplierId();
    }

    @Override
    public Byte value5() {
        return getActive();
    }

    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    @Override
    public Timestamp value7() {
        return getUpdateTime();
    }

    @Override
    public Timestamp value8() {
        return getReplyTime();
    }

    @Override
    public PrivateMessageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PrivateMessageRecord value2(String value) {
        setContent(value);
        return this;
    }

    @Override
    public PrivateMessageRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public PrivateMessageRecord value4(Integer value) {
        setReplierId(value);
        return this;
    }

    @Override
    public PrivateMessageRecord value5(Byte value) {
        setActive(value);
        return this;
    }

    @Override
    public PrivateMessageRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public PrivateMessageRecord value7(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public PrivateMessageRecord value8(Timestamp value) {
        setReplyTime(value);
        return this;
    }

    @Override
    public PrivateMessageRecord values(Integer value1, String value2, Integer value3, Integer value4, Byte value5, Timestamp value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrivateMessageRecord
     */
    public PrivateMessageRecord() {
        super(PrivateMessage.PRIVATE_MESSAGE);
    }

    /**
     * Create a detached, initialised PrivateMessageRecord
     */
    public PrivateMessageRecord(Integer id, String content, Integer userId, Integer replierId, Byte active, Timestamp createTime, Timestamp updateTime, Timestamp replyTime) {
        super(PrivateMessage.PRIVATE_MESSAGE);

        set(0, id);
        set(1, content);
        set(2, userId);
        set(3, replierId);
        set(4, active);
        set(5, createTime);
        set(6, updateTime);
        set(7, replyTime);
    }
}
