/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables.records;


import cn.treeshell.echo.model.entity.tables.Role;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 系统角色表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> implements Record8<Integer, String, String, String, Integer, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1058523614;

    /**
     * Setter for <code>echo.role.id</code>. id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>echo.role.id</code>. id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>echo.role.name</code>. 角色名称（汉字）
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>echo.role.name</code>. 角色名称（汉字）
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>echo.role.description</code>. 角色描述
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>echo.role.description</code>. 角色描述
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>echo.role.code</code>. 角色的英文code，如：ADMIN
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>echo.role.code</code>. 角色的英文code，如：ADMIN
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>echo.role.sort</code>. 角色顺序
     */
    public void setSort(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>echo.role.sort</code>. 角色顺序
     */
    public Integer getSort() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>echo.role.active</code>. 0：未删除，1：已删除
     */
    public void setActive(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>echo.role.active</code>. 0：未删除，1：已删除
     */
    public Byte getActive() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>echo.role.create_time</code>. 创建日期
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>echo.role.create_time</code>. 创建日期
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>echo.role.update_time</code>. 修改日期
     */
    public void setUpdateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>echo.role.update_time</code>. 修改日期
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, Integer, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, Integer, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Role.ROLE.ID;
    }

    @Override
    public Field<String> field2() {
        return Role.ROLE.NAME;
    }

    @Override
    public Field<String> field3() {
        return Role.ROLE.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Role.ROLE.CODE;
    }

    @Override
    public Field<Integer> field5() {
        return Role.ROLE.SORT;
    }

    @Override
    public Field<Byte> field6() {
        return Role.ROLE.ACTIVE;
    }

    @Override
    public Field<Timestamp> field7() {
        return Role.ROLE.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field8() {
        return Role.ROLE.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getCode();
    }

    @Override
    public Integer component5() {
        return getSort();
    }

    @Override
    public Byte component6() {
        return getActive();
    }

    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    @Override
    public Timestamp component8() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getCode();
    }

    @Override
    public Integer value5() {
        return getSort();
    }

    @Override
    public Byte value6() {
        return getActive();
    }

    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    @Override
    public Timestamp value8() {
        return getUpdateTime();
    }

    @Override
    public RoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RoleRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public RoleRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public RoleRecord value4(String value) {
        setCode(value);
        return this;
    }

    @Override
    public RoleRecord value5(Integer value) {
        setSort(value);
        return this;
    }

    @Override
    public RoleRecord value6(Byte value) {
        setActive(value);
        return this;
    }

    @Override
    public RoleRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public RoleRecord value8(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public RoleRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Byte value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(Role.ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(Integer id, String name, String description, String code, Integer sort, Byte active, Timestamp createTime, Timestamp updateTime) {
        super(Role.ROLE);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, code);
        set(4, sort);
        set(5, active);
        set(6, createTime);
        set(7, updateTime);
    }
}
