/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables.records;


import cn.treeshell.echo.model.entity.tables.Tag;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 文章标签表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagRecord extends UpdatableRecordImpl<TagRecord> implements Record6<Integer, String, Integer, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1829594247;

    /**
     * Setter for <code>echo.tag.id</code>. id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>echo.tag.id</code>. id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>echo.tag.name</code>. 标签名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>echo.tag.name</code>. 标签名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>echo.tag.category_id</code>. 分类id
     */
    public void setCategoryId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>echo.tag.category_id</code>. 分类id
     */
    public Integer getCategoryId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>echo.tag.active</code>. 0：未删除，1：已删除
     */
    public void setActive(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>echo.tag.active</code>. 0：未删除，1：已删除
     */
    public Byte getActive() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>echo.tag.create_time</code>. 创建日期
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>echo.tag.create_time</code>. 创建日期
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>echo.tag.update_time</code>. 修改日期
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>echo.tag.update_time</code>. 修改日期
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, Integer, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, Integer, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Tag.TAG.ID;
    }

    @Override
    public Field<String> field2() {
        return Tag.TAG.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Tag.TAG.CATEGORY_ID;
    }

    @Override
    public Field<Byte> field4() {
        return Tag.TAG.ACTIVE;
    }

    @Override
    public Field<Timestamp> field5() {
        return Tag.TAG.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field6() {
        return Tag.TAG.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getCategoryId();
    }

    @Override
    public Byte component4() {
        return getActive();
    }

    @Override
    public Timestamp component5() {
        return getCreateTime();
    }

    @Override
    public Timestamp component6() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getCategoryId();
    }

    @Override
    public Byte value4() {
        return getActive();
    }

    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    @Override
    public TagRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TagRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TagRecord value3(Integer value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public TagRecord value4(Byte value) {
        setActive(value);
        return this;
    }

    @Override
    public TagRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TagRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public TagRecord values(Integer value1, String value2, Integer value3, Byte value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagRecord
     */
    public TagRecord() {
        super(Tag.TAG);
    }

    /**
     * Create a detached, initialised TagRecord
     */
    public TagRecord(Integer id, String name, Integer categoryId, Byte active, Timestamp createTime, Timestamp updateTime) {
        super(Tag.TAG);

        set(0, id);
        set(1, name);
        set(2, categoryId);
        set(3, active);
        set(4, createTime);
        set(5, updateTime);
    }
}
