/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity;


import cn.treeshell.echo.model.entity.tables.*;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>echo</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARTICLE_PRIMARY = Indexes0.ARTICLE_PRIMARY;
    public static final Index ARTICLE_UK_TITLE = Indexes0.ARTICLE_UK_TITLE;
    public static final Index ARTICLE_CONTENT_PRIMARY = Indexes0.ARTICLE_CONTENT_PRIMARY;
    public static final Index ARTICLE_LIKE_PRIMARY = Indexes0.ARTICLE_LIKE_PRIMARY;
    public static final Index CATEGORY_PRIMARY = Indexes0.CATEGORY_PRIMARY;
    public static final Index CATEGORY_UK_NAME = Indexes0.CATEGORY_UK_NAME;
    public static final Index COMMENT_PRIMARY = Indexes0.COMMENT_PRIMARY;
    public static final Index COMMENT_LIKE_PRIMARY = Indexes0.COMMENT_LIKE_PRIMARY;
    public static final Index FEEDBACK_PRIMARY = Indexes0.FEEDBACK_PRIMARY;
    public static final Index FRIEND_LINK_PRIMARY = Indexes0.FRIEND_LINK_PRIMARY;
    public static final Index MENU_PRIMARY = Indexes0.MENU_PRIMARY;
    public static final Index NOTICE_PRIMARY = Indexes0.NOTICE_PRIMARY;
    public static final Index PRIVATE_MESSAGE_PRIMARY = Indexes0.PRIVATE_MESSAGE_PRIMARY;
    public static final Index ROLE_PRIMARY = Indexes0.ROLE_PRIMARY;
    public static final Index ROLE_MENU_PRIMARY = Indexes0.ROLE_MENU_PRIMARY;
    public static final Index TAG_PRIMARY = Indexes0.TAG_PRIMARY;
    public static final Index TAG_UK_NAME = Indexes0.TAG_UK_NAME;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_UK_USERNAME = Indexes0.USER_UK_USERNAME;
    public static final Index USER_ROLE_PRIMARY = Indexes0.USER_ROLE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ARTICLE_PRIMARY = Internal.createIndex("PRIMARY", Article.ARTICLE, new OrderField[] { Article.ARTICLE.ID }, true);
        public static Index ARTICLE_UK_TITLE = Internal.createIndex("uk_title", Article.ARTICLE, new OrderField[] { Article.ARTICLE.TITLE }, true);
        public static Index ARTICLE_CONTENT_PRIMARY = Internal.createIndex("PRIMARY", ArticleContent.ARTICLE_CONTENT, new OrderField[] { ArticleContent.ARTICLE_CONTENT.ID }, true);
        public static Index ARTICLE_LIKE_PRIMARY = Internal.createIndex("PRIMARY", ArticleLike.ARTICLE_LIKE, new OrderField[] { ArticleLike.ARTICLE_LIKE.ID }, true);
        public static Index CATEGORY_PRIMARY = Internal.createIndex("PRIMARY", Category.CATEGORY, new OrderField[] { Category.CATEGORY.ID }, true);
        public static Index CATEGORY_UK_NAME = Internal.createIndex("uk_name", Category.CATEGORY, new OrderField[] { Category.CATEGORY.NAME }, true);
        public static Index COMMENT_PRIMARY = Internal.createIndex("PRIMARY", Comment.COMMENT, new OrderField[] { Comment.COMMENT.ID }, true);
        public static Index COMMENT_LIKE_PRIMARY = Internal.createIndex("PRIMARY", CommentLike.COMMENT_LIKE, new OrderField[] { CommentLike.COMMENT_LIKE.ID }, true);
        public static Index FEEDBACK_PRIMARY = Internal.createIndex("PRIMARY", Feedback.FEEDBACK, new OrderField[] { Feedback.FEEDBACK.ID }, true);
        public static Index FRIEND_LINK_PRIMARY = Internal.createIndex("PRIMARY", FriendLink.FRIEND_LINK, new OrderField[] { FriendLink.FRIEND_LINK.ID }, true);
        public static Index MENU_PRIMARY = Internal.createIndex("PRIMARY", Menu.MENU, new OrderField[] { Menu.MENU.ID }, true);
        public static Index NOTICE_PRIMARY = Internal.createIndex("PRIMARY", Notice.NOTICE, new OrderField[] { Notice.NOTICE.ID }, true);
        public static Index PRIVATE_MESSAGE_PRIMARY = Internal.createIndex("PRIMARY", PrivateMessage.PRIVATE_MESSAGE, new OrderField[] { PrivateMessage.PRIVATE_MESSAGE.ID }, true);
        public static Index ROLE_PRIMARY = Internal.createIndex("PRIMARY", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index ROLE_MENU_PRIMARY = Internal.createIndex("PRIMARY", RoleMenu.ROLE_MENU, new OrderField[] { RoleMenu.ROLE_MENU.ID }, true);
        public static Index TAG_PRIMARY = Internal.createIndex("PRIMARY", Tag.TAG, new OrderField[] { Tag.TAG.ID }, true);
        public static Index TAG_UK_NAME = Internal.createIndex("uk_name", Tag.TAG, new OrderField[] { Tag.TAG.NAME }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_UK_USERNAME = Internal.createIndex("uk_username", User.USER, new OrderField[] { User.USER.USERNAME }, true);
        public static Index USER_ROLE_PRIMARY = Internal.createIndex("PRIMARY", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ID }, true);
    }
}
