/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity;


import cn.treeshell.echo.model.entity.tables.Article;
import cn.treeshell.echo.model.entity.tables.ArticleContent;
import cn.treeshell.echo.model.entity.tables.ArticleLike;
import cn.treeshell.echo.model.entity.tables.Category;
import cn.treeshell.echo.model.entity.tables.Comment;
import cn.treeshell.echo.model.entity.tables.CommentLike;
import cn.treeshell.echo.model.entity.tables.Feedback;
import cn.treeshell.echo.model.entity.tables.FriendLink;
import cn.treeshell.echo.model.entity.tables.Menu;
import cn.treeshell.echo.model.entity.tables.Notice;
import cn.treeshell.echo.model.entity.tables.PrivateMessage;
import cn.treeshell.echo.model.entity.tables.Role;
import cn.treeshell.echo.model.entity.tables.RoleMenu;
import cn.treeshell.echo.model.entity.tables.Tag;
import cn.treeshell.echo.model.entity.tables.User;
import cn.treeshell.echo.model.entity.tables.UserRole;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in echo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 文章表
     */
    public static final Article ARTICLE = Article.ARTICLE;

    /**
     * 文章内容表
     */
    public static final ArticleContent ARTICLE_CONTENT = ArticleContent.ARTICLE_CONTENT;

    /**
     * 用户点赞文章表
     */
    public static final ArticleLike ARTICLE_LIKE = ArticleLike.ARTICLE_LIKE;

    /**
     * 文章分类表
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * 评论表
     */
    public static final Comment COMMENT = Comment.COMMENT;

    /**
     * 用户点赞评论表
     */
    public static final CommentLike COMMENT_LIKE = CommentLike.COMMENT_LIKE;

    /**
     * 反馈表
     */
    public static final Feedback FEEDBACK = Feedback.FEEDBACK;

    /**
     * 友链表
     */
    public static final FriendLink FRIEND_LINK = FriendLink.FRIEND_LINK;

    /**
     * 系统菜单表
     */
    public static final Menu MENU = Menu.MENU;

    /**
     * 通知表
     */
    public static final Notice NOTICE = Notice.NOTICE;

    /**
     * 悄悄话表
     */
    public static final PrivateMessage PRIVATE_MESSAGE = PrivateMessage.PRIVATE_MESSAGE;

    /**
     * 系统角色表
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * 角色权限关系表
     */
    public static final RoleMenu ROLE_MENU = RoleMenu.ROLE_MENU;

    /**
     * 文章标签表
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * 用户表
     */
    public static final User USER = User.USER;

    /**
     * 用户角色关系表
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
