/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables;


import cn.treeshell.echo.model.entity.Echo;
import cn.treeshell.echo.model.entity.Indexes;
import cn.treeshell.echo.model.entity.Keys;
import cn.treeshell.echo.model.entity.tables.records.FriendLinkRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 友链表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FriendLink extends TableImpl<FriendLinkRecord> {

    private static final long serialVersionUID = -1001790071;

    /**
     * The reference instance of <code>echo.friend_link</code>
     */
    public static final FriendLink FRIEND_LINK = new FriendLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FriendLinkRecord> getRecordType() {
        return FriendLinkRecord.class;
    }

    /**
     * The column <code>echo.friend_link.id</code>. id
     */
    public final TableField<FriendLinkRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "id");

    /**
     * The column <code>echo.friend_link.title</code>. 博客标题
     */
    public final TableField<FriendLinkRecord, String> TITLE = createField(DSL.name("title"), org.jooq.impl.SQLDataType.VARCHAR(40).nullable(false), this, "博客标题");

    /**
     * The column <code>echo.friend_link.url</code>. 博客地址
     */
    public final TableField<FriendLinkRecord, String> URL = createField(DSL.name("url"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "博客地址");

    /**
     * The column <code>echo.friend_link.image_url</code>. 博客图标地址
     */
    public final TableField<FriendLinkRecord, String> IMAGE_URL = createField(DSL.name("image_url"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "博客图标地址");

    /**
     * The column <code>echo.friend_link.email</code>. 联系人邮箱
     */
    public final TableField<FriendLinkRecord, String> EMAIL = createField(DSL.name("email"), org.jooq.impl.SQLDataType.VARCHAR(30).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "联系人邮箱");

    /**
     * The column <code>echo.friend_link.active</code>. 0：未删除，1：已删除
     */
    public final TableField<FriendLinkRecord, Byte> ACTIVE = createField(DSL.name("active"), org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "0：未删除，1：已删除");

    /**
     * The column <code>echo.friend_link.create_time</code>. 创建日期
     */
    public final TableField<FriendLinkRecord, Timestamp> CREATE_TIME = createField(DSL.name("create_time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建日期");

    /**
     * The column <code>echo.friend_link.update_time</code>. 修改日期
     */
    public final TableField<FriendLinkRecord, Timestamp> UPDATE_TIME = createField(DSL.name("update_time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改日期");

    /**
     * Create a <code>echo.friend_link</code> table reference
     */
    public FriendLink() {
        this(DSL.name("friend_link"), null);
    }

    /**
     * Create an aliased <code>echo.friend_link</code> table reference
     */
    public FriendLink(String alias) {
        this(DSL.name(alias), FRIEND_LINK);
    }

    /**
     * Create an aliased <code>echo.friend_link</code> table reference
     */
    public FriendLink(Name alias) {
        this(alias, FRIEND_LINK);
    }

    private FriendLink(Name alias, Table<FriendLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private FriendLink(Name alias, Table<FriendLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("友链表"));
    }

    public <O extends Record> FriendLink(Table<O> child, ForeignKey<O, FriendLinkRecord> key) {
        super(child, key, FRIEND_LINK);
    }

    @Override
    public Schema getSchema() {
        return Echo.ECHO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FRIEND_LINK_PRIMARY);
    }

    @Override
    public Identity<FriendLinkRecord, Integer> getIdentity() {
        return Keys.IDENTITY_FRIEND_LINK;
    }

    @Override
    public UniqueKey<FriendLinkRecord> getPrimaryKey() {
        return Keys.KEY_FRIEND_LINK_PRIMARY;
    }

    @Override
    public List<UniqueKey<FriendLinkRecord>> getKeys() {
        return Arrays.<UniqueKey<FriendLinkRecord>>asList(Keys.KEY_FRIEND_LINK_PRIMARY);
    }

    @Override
    public FriendLink as(String alias) {
        return new FriendLink(DSL.name(alias), this);
    }

    @Override
    public FriendLink as(Name alias) {
        return new FriendLink(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FriendLink rename(String name) {
        return new FriendLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FriendLink rename(Name name) {
        return new FriendLink(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, String, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
