/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables;


import cn.treeshell.echo.model.entity.Echo;
import cn.treeshell.echo.model.entity.Indexes;
import cn.treeshell.echo.model.entity.Keys;
import cn.treeshell.echo.model.entity.tables.records.PrivateMessageRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 悄悄话表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrivateMessage extends TableImpl<PrivateMessageRecord> {

    private static final long serialVersionUID = 1227679836;

    /**
     * The reference instance of <code>echo.private_message</code>
     */
    public static final PrivateMessage PRIVATE_MESSAGE = new PrivateMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PrivateMessageRecord> getRecordType() {
        return PrivateMessageRecord.class;
    }

    /**
     * The column <code>echo.private_message.id</code>. id
     */
    public final TableField<PrivateMessageRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "id");

    /**
     * The column <code>echo.private_message.content</code>. 悄悄话内容
     */
    public final TableField<PrivateMessageRecord, String> CONTENT = createField(DSL.name("content"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "悄悄话内容");

    /**
     * The column <code>echo.private_message.user_id</code>. 发送悄悄话用户id
     */
    public final TableField<PrivateMessageRecord, Integer> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "发送悄悄话用户id");

    /**
     * The column <code>echo.private_message.replier_id</code>. 回复悄悄话用户id
     */
    public final TableField<PrivateMessageRecord, Integer> REPLIER_ID = createField(DSL.name("replier_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "回复悄悄话用户id");

    /**
     * The column <code>echo.private_message.active</code>. 0：未删除，1：已删除
     */
    public final TableField<PrivateMessageRecord, Byte> ACTIVE = createField(DSL.name("active"), org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "0：未删除，1：已删除");

    /**
     * The column <code>echo.private_message.create_time</code>. 创建日期
     */
    public final TableField<PrivateMessageRecord, Timestamp> CREATE_TIME = createField(DSL.name("create_time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建日期");

    /**
     * The column <code>echo.private_message.update_time</code>. 修改日期
     */
    public final TableField<PrivateMessageRecord, Timestamp> UPDATE_TIME = createField(DSL.name("update_time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改日期");

    /**
     * The column <code>echo.private_message.reply_time</code>. 回复日期
     */
    public final TableField<PrivateMessageRecord, Timestamp> REPLY_TIME = createField(DSL.name("reply_time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "回复日期");

    /**
     * Create a <code>echo.private_message</code> table reference
     */
    public PrivateMessage() {
        this(DSL.name("private_message"), null);
    }

    /**
     * Create an aliased <code>echo.private_message</code> table reference
     */
    public PrivateMessage(String alias) {
        this(DSL.name(alias), PRIVATE_MESSAGE);
    }

    /**
     * Create an aliased <code>echo.private_message</code> table reference
     */
    public PrivateMessage(Name alias) {
        this(alias, PRIVATE_MESSAGE);
    }

    private PrivateMessage(Name alias, Table<PrivateMessageRecord> aliased) {
        this(alias, aliased, null);
    }

    private PrivateMessage(Name alias, Table<PrivateMessageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("悄悄话表"));
    }

    public <O extends Record> PrivateMessage(Table<O> child, ForeignKey<O, PrivateMessageRecord> key) {
        super(child, key, PRIVATE_MESSAGE);
    }

    @Override
    public Schema getSchema() {
        return Echo.ECHO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIVATE_MESSAGE_PRIMARY);
    }

    @Override
    public Identity<PrivateMessageRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PRIVATE_MESSAGE;
    }

    @Override
    public UniqueKey<PrivateMessageRecord> getPrimaryKey() {
        return Keys.KEY_PRIVATE_MESSAGE_PRIMARY;
    }

    @Override
    public List<UniqueKey<PrivateMessageRecord>> getKeys() {
        return Arrays.<UniqueKey<PrivateMessageRecord>>asList(Keys.KEY_PRIVATE_MESSAGE_PRIMARY);
    }

    @Override
    public PrivateMessage as(String alias) {
        return new PrivateMessage(DSL.name(alias), this);
    }

    @Override
    public PrivateMessage as(Name alias) {
        return new PrivateMessage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PrivateMessage rename(String name) {
        return new PrivateMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PrivateMessage rename(Name name) {
        return new PrivateMessage(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, Integer, Integer, Byte, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
