/*
 * This file is generated by jOOQ.
 */
package cn.treeshell.echo.model.entity.tables;


import cn.treeshell.echo.model.entity.Echo;
import cn.treeshell.echo.model.entity.Indexes;
import cn.treeshell.echo.model.entity.Keys;
import cn.treeshell.echo.model.entity.tables.records.RoleMenuRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 角色权限关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleMenu extends TableImpl<RoleMenuRecord> {

    private static final long serialVersionUID = 424420732;

    /**
     * The reference instance of <code>echo.role_menu</code>
     */
    public static final RoleMenu ROLE_MENU = new RoleMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoleMenuRecord> getRecordType() {
        return RoleMenuRecord.class;
    }

    /**
     * The column <code>echo.role_menu.id</code>. id
     */
    public final TableField<RoleMenuRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "id");

    /**
     * The column <code>echo.role_menu.role_id</code>. 角色id
     */
    public final TableField<RoleMenuRecord, Integer> ROLE_ID = createField(DSL.name("role_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "角色id");

    /**
     * The column <code>echo.role_menu.menu_id</code>. 权限id
     */
    public final TableField<RoleMenuRecord, Integer> MENU_ID = createField(DSL.name("menu_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "权限id");

    /**
     * The column <code>echo.role_menu.active</code>. 0：未删除，1：已删除
     */
    public final TableField<RoleMenuRecord, Byte> ACTIVE = createField(DSL.name("active"), org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "0：未删除，1：已删除");

    /**
     * The column <code>echo.role_menu.create_time</code>. 创建日期
     */
    public final TableField<RoleMenuRecord, Timestamp> CREATE_TIME = createField(DSL.name("create_time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建日期");

    /**
     * The column <code>echo.role_menu.update_time</code>. 修改日期
     */
    public final TableField<RoleMenuRecord, Timestamp> UPDATE_TIME = createField(DSL.name("update_time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改日期");

    /**
     * Create a <code>echo.role_menu</code> table reference
     */
    public RoleMenu() {
        this(DSL.name("role_menu"), null);
    }

    /**
     * Create an aliased <code>echo.role_menu</code> table reference
     */
    public RoleMenu(String alias) {
        this(DSL.name(alias), ROLE_MENU);
    }

    /**
     * Create an aliased <code>echo.role_menu</code> table reference
     */
    public RoleMenu(Name alias) {
        this(alias, ROLE_MENU);
    }

    private RoleMenu(Name alias, Table<RoleMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoleMenu(Name alias, Table<RoleMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("角色权限关系表"));
    }

    public <O extends Record> RoleMenu(Table<O> child, ForeignKey<O, RoleMenuRecord> key) {
        super(child, key, ROLE_MENU);
    }

    @Override
    public Schema getSchema() {
        return Echo.ECHO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ROLE_MENU_PRIMARY);
    }

    @Override
    public Identity<RoleMenuRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ROLE_MENU;
    }

    @Override
    public UniqueKey<RoleMenuRecord> getPrimaryKey() {
        return Keys.KEY_ROLE_MENU_PRIMARY;
    }

    @Override
    public List<UniqueKey<RoleMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<RoleMenuRecord>>asList(Keys.KEY_ROLE_MENU_PRIMARY);
    }

    @Override
    public RoleMenu as(String alias) {
        return new RoleMenu(DSL.name(alias), this);
    }

    @Override
    public RoleMenu as(Name alias) {
        return new RoleMenu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleMenu rename(String name) {
        return new RoleMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleMenu rename(Name name) {
        return new RoleMenu(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
